# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 2m

linters:
  disable-all: true
  enable:
    - asciicheck
    #- bodyclose
    #- deadcode
    #- depguard
    #- dogsled
    #- dupl
    #- errcheck
    #- errorlint
    #- exhaustive
    #- exhaustivestruct
    #- exportloopref
    #- funlen
    #- gci
    #- gochecknoglobals
    #- gochecknoinits
    #- gocognit
    #- goconst
    #- gocritic
    #- gocyclo
    #- godot
    #- godox
    #- goerr113
    #- gofmt
    #- gofumpt
    #- goheader
    #- goimports
    #- golint
    #- gomnd
    #- gomodguard
    #- goprintffuncname
    #- gosec
    #- gosimple
    #- govet
    #- ineffassign
    #- interfacer
    #- lll
    #- maligned
    #- misspell
    #- nakedret
    #- nestif
    #- nlreturn
    #- noctx
    #- nolintlint
    #- prealloc
    #- rowserrcheck
    #- scopelint
    #- sqlclosecheck
    #- staticcheck
    #- structcheck
    #- stylecheck
    #- testpackage
    #- tparallel
    #- typecheck
    #- unconvert
    #- unparam
    #- unused
    #- varcheck
    #- whitespace
    #- wrapcheck
    #- wsl

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupl
